export default interface ClinicalTrialDetails {
	NCTId: string;
	OrgFullName: string;
	BriefTitle: string;
	OfficialTitle: string;
	StatusVerifiedDate: string;
	OverallStatus: string;
	StartDate: string;
	PrimaryCompletionDate: string;
	ResponsiblePartyType: string;
	LeadSponsorName: string;
	LeadSponsorClass: string;
	CollaboratorName: string;
	BriefSummary: string;
	DetailedDescription: string;
	ArmGroupLabel: string;
	ArmGroupDescription: string;
	ArmGroupInterventionName: string;
	InterventionType: string;
	InterventionName: string;
	InterventionDescription: string;
	InterventionArmGroupLabel: string;
	InterventionOtherName: string;
	PrimaryOutcomeMeasure: string;
	PrimaryOutcomeDescription: string;
	PrimaryOutcomeTimeFrame: string;
	SecondaryOutcomeMeasure: string;
	SecondaryOutcomeDescription: string;
	SecondaryOutcomeTimeFrame: string;
	EligibilityCriteria: string;
	HealthyVolunteers: string;
	Gender: string;
	MaximumAge: string | null;
	StdAge: string;
	OverallOfficialName: string;
	OverallOfficialAffiliation: string;
	OverallOfficialRole: string;
	LocationFacility: string;
	LocationStatus: string;
	LocationCity: string;
	LocationState: string;
	LocationZip: string;
	LocationCountry: string;
	LocationContactName: string;
	LocationContactRole: string;
	LocationContactEMail: string;
	LocationContactPhone: string;
	LocationContactPhoneExt: string;
	MinimumAge: string | null; // Value can be null, so it's set as 'any' to handle both cases
	DesignPrimaryPurpose?: any; // Value can be null, so it's set as 'any' to handle both cases
}
